FarmersMarket/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf import settings

# To use the built in user authentication module.
from django.contrib.auth import views as auth_views
# <<<<<<< HEAD
# =======
# from updater import views

# >>>>>>> 8b569914b8e9021887767e8c5cbc6a6e7a10ae12

from django.contrib.auth.views import LogoutView, LoginView
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="shop_thanks"),
    path('admin/', admin.site.urls),
    url(r"^farmer/", include("farmer.urls", namespace="farmer")),
    url(r"^trader/", include("trader.urls", namespace="trader")),
    url(r"^blog/", include("blog.urls", namespace="blog")),

    url(r'^login/$', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    url(r"^blog/", include("django.contrib.auth.urls")),

    url('cart', include('cart.urls')),
    url('orders/', include('orders.urls')),
    url('shop/', include('shop.urls')),

    path("update_server/", views.update, name="update"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from blog import views

# For template tagging.

app_name = 'blog'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse_lazy("blog:post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse_lazy("blog:post_list")

    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from blog.models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author','title', 'text',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from blog.models import Post, Comment
from django.utils import timezone
from blog.forms import PostForm, CommentForm

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

# this allows me to use django's ORM (Object Relation Model.)
# __lte means less than or equal to
    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

#######################################
## Functions that require a pk match ##
#######################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

# @login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

blog/templates/blog/blog_base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>FARMERS' MARKET BLOG</title>

        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


        <!--  MEDIUM STYLE EDITOR -->
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

        <!-- {# Fonts#} -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
      </head>

<body class='loader'>

  <nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">

      <ul class="nav navbar-nav">
        <li><a class='navbar-brand bigbrand' href="{% url 'blog:post_list' %}">FARMERS' MARKET BLOG</a></li>
        <li><a href="{% url 'home'%}">About Farmers' Market</a></li>
        <li><a href="{% url 'home' %}">BACK TO MARKET</a></li>
        <!-- <li><a href="https://www.linkedin.com">LinkedIn</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'blog:post_new' %}" >New Post</a>
        </li>

        <li>
          <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
        </li>
        <li>
          <a href="{% url 'logout' %}" >Log out</a>
        </li>

        <li>
          <a>Welcome: {{ user.username }}</a>
        </li>
          {% else %}
          <li><a class='nav navbar-right' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span></a></li>
        {% endif %}

      </ul>
  </div>
</nav>

  <!-- {# The actual blog posts#} -->
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                  <div class="blog_posts">
                    {% block content %}
                    {% endblock %}

                  </div>

                </div>
            </div>
        </div>

<!-- {# SCRIPTS#} -->

<script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends "blog/blog_base.html" %}
{% load bootstrap3 %}
{% block content %}

<h2>New Comment:</h2>
<div class="container">
  <div class="jumbotron">
    <form class="post-form" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}

      <button type="submit" class="save btn btn-default">Submit Comment</button>
    </form>
  </div>

</div>


<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/blog_base.html" %}
{% block content %}

  <form method="POST">
    {% csrf_token %}

    <p>Are you sure you want to delete : {{object}}?</p>

    <input type="submit" class="btn btn-danger" value="YES, Delete {{object}}"> <br>
    <a href="{% url 'blog:post_detail' pk=post.pk %}">CANCEL</a>
  </form>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/blog_base.html" %}
{% block content %}


<div class="container">
  <div class="jumbotron">
    <h1 class="posttitle loader">{{post.title}}</h1>

    {% if post.published_date %}

    <div class="date postdate">
      {{post.published_date}}
    </div>
    {% else %}

    <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">PUBLISH POST</a>

    {% endif %}

    <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
      <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>

      <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
        <span class="glyphicon glyphicon-remove"></span>
      </a>
    {% endif %}

    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

    <div class="container">
      {% for comment in post.comments.all %}
      <br>
      {% if user.is_authenticated or comment.approved_comment %}
        {{comment.created_date}}
          {% if not comment.approved_comment %}
            <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
              <span class="glyphicon glyphicon-remove"></span>
            </a>
            <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
              <span class="glyphicon glyphicon-ok"></span>
            </a>
          {% endif %}
            <p>{{comment.text|safe|linebreaks}}</p>
            <p>Posted by {{comment.author}}</p>
      {% endif %}
      {% empty %}
      <p>No Comments!!</p>
      {% endfor %}
    </div>
  </div>

</div>


{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "blog/blog_base.html" %}
{% block content %}

{% for post in posts %}

  <div class="post">

    <p class="date"> Created: {{post.created_date|date:'d-m-Y'}}</p>
    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>

    <p>{{post.text|truncatechars:200}}</p>

  </div>

{% endfor %}

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/blog_base.html" %}
{% load bootstrap3 %}
{% block content %}

<h2>NEW POST</h2>

<div class="container">
  <div class="jumbotron">
    <form class="post-form" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}

      <button type="submit" class="save btn btn-default">SUBMIT POST</button>
    </form>

  </div>

</div>


<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/blog_base.html" %}
{% block content %}


<div class="container">
  <div class="jumbotron">
    <div class="centerstage">

      {% for post in post_list %}

        <div class="post">

          <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
          <div class="date">
              <p>Published on: {{ post.published_date|date:"D M Y"}}</p>
          </div>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>

      {% endfor %}

    </div>
  </div>

</div>


{% endblock %}