FarmersMarket/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf import settings

# To use the built in user authentication module.
from django.contrib.auth import views as auth_views
# <<<<<<< HEAD
# =======
# from updater import views

# >>>>>>> 8b569914b8e9021887767e8c5cbc6a6e7a10ae12

from django.contrib.auth.views import LogoutView, LoginView
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="shop_thanks"),
    path('admin/', admin.site.urls),
    url(r"^farmer/", include("farmer.urls", namespace="farmer")),
    url(r"^trader/", include("trader.urls", namespace="trader")),
    url(r"^blog/", include("blog.urls", namespace="blog")),

    url(r'^login/$', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    url(r"^blog/", include("django.contrib.auth.urls")),

    url('cart', include('cart.urls')),
    url('orders/', include('orders.urls')),
    url('shop/', include('shop.urls')),

    path("update_server/", views.update, name="update"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from blog import views

# For template tagging.

app_name = 'blog'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
]

farmer/urls.py
from django.conf.urls import url

from . import views

app_name='farmer'

urlpatterns = [
    url(r"^$", views.FarmerList.as_view(), name="all"),
    url(r"new/$", views.RegisterFarmer.as_view(), name="farmer_registration"),
    url(r'^(?P<pk>\d+)/$', views.FarmerDetails.as_view(), name='farmer_detail'),
    # url(r"details",views.FarmerDetail.as_view(),name="farmer"),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

    url(r"login/$", views.LoginUserView.as_view(), name='shop_login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="shop_logout"),
    url(r"signup/$", views.signup, name="shop_signup"),
]

trader/urls.py
from django.conf.urls import url
from . import views

app_name='trader'

urlpatterns = [
    url(r"^$", views.TraderList.as_view(), name="all_traders"),
    url(r"new/$", views.RegisterTrader.as_view(), name="trader_registration"),
    url(r'^(?P<pk>\d+)/$', views.TraderDetails.as_view(), name='trader_detail'),
    # url(r"details",views.FarmerDetail.as_view(),name="farmer"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Farmers Market</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">


  </head>


  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">FARMERS' MARKET</a>

    					<ul class="nav navbar-nav navbar-right">

                      <li class="nav-item active">
                        <a href="{% url 'register' %}" class="nav-link">REGISTER</a>
                      </li>
                      <li class="nav-item active">
                        <a href="{% url 'farmer:all' %}" class="nav-link">FARMERS</a>
                      </li>
                      <li class="nav-item active">
                        <a href="{% url 'trader:all_traders' %}" class="nav-link">TRADERS</a>
                      </li>
                      <li class="nav-item active">
                        <a href="{% url 'blog:post_list' %}" class="nav-link">BLOG</a>
                      </li>
    						      <li class="nav-item active">
                        <a href="{% url 'shop:product_list' %}"class="nav-link">MARKET AREA</a>
                      </li>

    					</ul>

    			</div>
    		</nav>
        <br>

          {% block content %}
          <br>
         <div class="container">
           <br>

            <div class="jumbotron">

              </div>
            </div>

          {% endblock %}



<div class="footer">

<div class="container">
  <p> Coded with love by <a href="{#}">Farm Love</a></p>
    <p>|<a href="{% url 'register' %}" class="btn btn-default">REGISTER</a>|
    <a href="{% url 'farmer:all' %}" class="btn btn-default">FARMERS</a>|
    <a href="{% url 'trader:all_traders' %}" class="btn btn-default">TRADERS</a>|
    <a href="{% url 'blog:post_list' %}" class="btn btn-default">BLOG</a>|
    <a href="{% url 'shop:product_list' %}" class="btn btn-default">MARKET AREA</a>|

</div>

</div>

  </body>
</html>

templates/index.html
{% extends 'base.html'%}

{% block content %}

<br><br>

<div class="container">

  <div class="jumbotron">
    <h2>Welcome to the official and legit Farmers Market platform.</h2>
    <p>If you have a product and you are looking for the right customers, this platform is yours.</p>
    <p>And if you are a market vendor looking for fresh produce, this platform is yours too.</p>
    <p>If you are a consumer looking for quality farm products, our shop has it all</p>

    <h2> Let's get your perfect match:</h2>

    <form class="text-center border border-light p-5" method="POST">
      {% csrf_token %}
      <h2>AM A: </h2>
<br>
      <h2><a href="{% url 'farmer:farmer_registration' %}" class="btn btn-primary form-control">FARMER</a></h2>
<br>
    <h2><a href="{% url 'trader:trader_registration' %}" class="btn btn-primary form-control">TRADER</a></h2>
<br>
    <h2><a href="{% url 'shop:product_list' %}" class="btn btn-primary form-control">CONSUMER</a></h2>
    </form>
  </div>

</div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
  <br>
  <div class="jumbotron">
    <h2>Welcome To The Registration Page:</h2>
    <h3>Register as: </h3>
    <h2><a href="{% url 'farmer:farmer_registration' %}" class="btn btn-primary">A FARMER</a></h2>
    <hr>
    <h3>OR</h3>
    <h2><a href="{% url 'trader:trader_registration' %}" class="btn btn-primary">A TRADER</a></h2>
  </div>

</div>


{% endblock %}

templates/thanks.html
{% extends 'market_base.html' %}

{% block content %}

<div class="container">

  <div class="jumbotron">

    <h3>Thanks for shopping with us. </h3>

  </div>

</div>

{% end block %}